version: '2.1'

services:
  build:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: usps
    entrypoint: [ "go", "build", "cmd/usps-util.go" ]
    volumes:
      - ..:/go/src/github.com/justinbarrick/usps-api

  test:
    extends:
      service: build
    entrypoint: [ "go", "test" ]
